#数据源配置
spring:
  redis:
    ##redis 单机环境配置
##    生产环境
    host: 8.134.14.207
    port: 54328
#    正式环境
#    host: 172.17.0.5
#    port: 6379
#    host: 10.186.1.241
#    port: 6379
#    password: redis@2021*
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    # MySql
#    url: jdbc:mysql://172.17.0.4:3306/bladextest?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://8.134.14.207:54325/bladextest?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.186.1.243:54325/marketing?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: gdtec@2021*
    # PostgreSQL
    #url: jdbc:postgresql://127.0.0.1:5432/bladex_boot
    #username: postgres
    #password: 123456
    # Oracle
    #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    #username: BLADEX_BOOT
    #password: BLADEX_BOOT
    # SqlServer
    #url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=bladex_boot
    #username: bladex_boot
    #password: bladex_boot
oss:
  enable: true
  name: minio
  tenant-mode: false
  endpoint: http://8.134.14.207:54329/
#  endpoint: http://172.17.0.6:54329/
#  endpoint: http://10.186.1.251:54329/
  access-key: adminio
  secret-key: gdtec@minio
#第三方登陆
social:
  enabled: false
  domain: http://127.0.0.1:1888

#blade配置
blade:
  #分布式锁配置
  lock:
    ##是否启用分布式锁
    enabled: false
    ##redis服务地址
    address: redis://127.0.0.1:6379
  #本地文件上传
  file:
    remote-mode: true
    upload-domain: http://localhost:8999
    remote-path: /usr/share/nginx/html

#AD验证
adloginsetting:
  enable: false
  url: ldap://10.188.188.240:389/
  factory: com.sun.jndi.ldap.LdapCtxFactory
